name: Deploy Frontend to EC2 with Docker

on:
  push:
    branches:
      - develop             # develop 브랜치 푸시 시
      - feat/**             # feat/** 브랜치 푸시 시

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Docker 이미지 빌드 및 Docker Hub 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      # 3️⃣ Docker 이미지 빌드 및 푸시
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_NAME }}/booktown-frontend:latest .
          docker push ${{ secrets.DOCKER_NAME }}/booktown-frontend:latest

      # 4️⃣ EC2에 SSH로 접속하여 기존 컨테이너 종료 및 새 컨테이너 실행
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            # 기존 컨테이너 종료 및 삭제
            docker stop booktown-frontend || true
            docker rm booktown-frontend || true

            # 최신 Docker 이미지 가져오기
            docker pull ${{ secrets.DOCKER_NAME }}/booktown-frontend:latest

            # 새 컨테이너 실행 (Nginx 기반)
            docker run -d --name booktown-frontend -p 80:80 \
              --restart always \
              ${{ secrets.DOCKER_NAME }}/booktown-frontend:latest
