name: Deploy Frontend to EC2

on:
  pull_request:
    branches: [main, develop] # PR 발생시
  push:
    branches:
      - develop             # develop 브랜치 푸시 시
      - feat/**             # feat/** 브랜치 푸시 시

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16, 18, 20]  
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}  

      - name: Install dependencies
        run: |
          cd BookTown_Front_end 
          npm install  

      - name: Build React app
        run: |
          cd BookTown_Front_end  
          npm run build  

      - name: Deploy to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "build/*"
          target: "/home/ec2-user/BookTown_Front_end/"

      - name: Restart Nginx
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo systemctl restart nginx

